// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxzpyrsglniohutwzhlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4enB5cnNnbG5pb2h1dHd6aGxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MDUyMzgsImV4cCI6MjA1MDE4MTIzOH0.UGjGrAJePzoZapGU5JI4yicMKse5HneYG6Ncu01tFjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);